### ISSUE TITLE
Issues with filenames containing spaces/special characters

### ISSUE THREAD

**Issue by herrbischoff** [chrissimpkins/Crunch#1]
I just testes Crunch with a file named `MILITARY 2016-04-10 15.47.11.png` (a screenshot from the console game Military Madness). Stage 1 worked somehow, Stage 2 did not at all:

```
• • • Crunching /Users/[REDACTED]/MILITARY 2016-04-10 15.47.11.png...
 
Original size (kB): 	471.940
 
==> Running stage 1 optimizations...
stat: /Users/[REDACTED]/MILITARY 2016-04-10 15-crunch.png: stat: No such file or directory
 
(standard_in) 1: parse error
Current size (kB): 	0.000
 
==> Running stage 2 optimizations...
==> Hold tight.  This could take awhile.
==> Click Cancel at any time to save at the above size.
[ERROR] Unable to access the file for optimizations.  Please report this issue.
stat: /Users/[REDACTED]/MILITARY 2016-04-10 15-crunch.png: stat: No such file or directory
 
---
Optimized filepath: /Users/[REDACTED]/MILITARY 2016-04-10 15-crunch.png
(standard_in) 1: parse error
Final size  (kB): 	0.000
(standard_in) 1: parse error
Percent original: 	0.00%
(standard_in) 1: parse error
Space saved (kB): 	0.000
---
```

**Comment by chrissimpkins** [comment]
mind confirming that it works when you remove all special characters?

**Comment by herrbischoff** [comment]
Already did, sorry for not including this. When the filename is just `MILITARY.png`, it works as it should.

**Comment by chrissimpkins** [comment]
Thank you very much!  Can you confirm that the following command does not cause an error:

```
$ stat  "/Users/[REDACTED]/MILITARY 2016-04-10 15.47.11.png"
```

**Comment by herrbischoff** [comment]
Here's the result:

```
stat: cannot read file system information for '%z': No such file or directory
  File: "/Users/[REDACTED]/MILITARY 2016-04-10 15.47.11.png"
    ID: 100000500000011 Namelen: *       Type: hfs
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 102207488  Free: 30651255   Available: 30587255
Inodes: Total: 102207486  Free: 30587255
```

**Comment by herrbischoff** [comment]
I believe you wanted to get the "time of last status change, human-readable". This does not work together with the `-f` flag.

**Comment by chrissimpkins** [comment]
Using this to obtain file size with the stat executable.  It looks like it is an exception being raised by `stat` with that path.  Trying to figure out whether it is a stat issue, or an issue on my end.

**Comment by chrissimpkins** [comment]
This is executed with each new image file so it works with the files that have paths without special chars, doesn't in those with special chars based upon what you are showing here.

**Comment by herrbischoff** [comment]
I believe any drag-and-drop application should compensate for that.

**Comment by herrbischoff** [comment]
BTW, I also found that Crunch overwrites files with the same name without asking. It should rename its output accordingly.

**Comment by chrissimpkins** [comment]
Yeah, I may have to adjust the paths when they include special chars.  This is definitely a valid and important issue.

**Comment by chrissimpkins** [comment]
> I also found that Crunch overwrites files with the same name without asking

Only previously compressed versions with the [filename]-crunch.png naming scheme.  It should never overwrite the original.  Are you seeing original overwrites?

**Comment by herrbischoff** [comment]
Nope. I was referring to the [filename]-crunch.png naming scheme. If you feel this is not a problem, just disregard. It was something I noticed, because most applications handle existing files differently, that is all.

**Comment by herrbischoff** [comment]
And another observation: Crunch is doing a remarkably better job than ImageOptim for PNGs. The same files was reduced to 189k with ImageOptim and 95k with Crunch. Just wow. :)

**Comment by chrissimpkins** [comment]
It uses a selectively lossy PNG optimization approach.  It will definitely produce better results on many PNG files (see [benchmarks](https://github.com/chrissimpkins/Crunch/blob/master/BENCHMARKS.md)) at the cost of a relatively minor reduction in image quality.  So far to me this has been imperceptible.

Thanks for all of these comments and tests. I really appreciate your time.  I will try to work these fixes in.

**Comment by chrissimpkins** [comment]
Added existing write file path handling as #2 

Thanks again!

**Comment by herrbischoff** [comment]
You're welcome. Let me know when you could use a second pair of hands and eyes to verify something.

**Comment by chrissimpkins** [comment]
Greatly appreciated.  That is a daily occurrence so you may not completely understand what you just offered 😉

**Comment by herrbischoff** [comment]
Just shoot, i'll duck if I need to. :D

**Comment by chrissimpkins** [comment]
Deal!

**Comment by chrissimpkins** [comment]
As a side note, the developer who wrote that pathing code in the original issue report deserves a smack :)

**Comment by chrissimpkins** [comment]
Can you confirm that there is actually a literal `/Users/[REDACTED]/` directory path on your system?  I replicated this filepath and stat works from the command line when the file path is quoted.  Verifying that I am not missing quotes around the path variables in the application.

**Comment by chrissimpkins** [comment]
Interesting. It seems to be the directory path surrounded by brackets, but only when the working directory is one level above that syntax.

stat works on a directory one level below with that naming:

```
~/Desktop/images
▶ stat -f %z "[REDACTED]/MILITARY 2016-04-10 15.47.11.png"
3529
```

but not two levels below:

```
~/Desktop
▶ stat -f %z "/images/[REDACTED]/MILITARY 2016-04-10 15.47.11.png"
stat: /images/[REDACTED]/MILITARY 2016-04-10 15.47.11.png: stat: No such file or directory
```

Let me give this some thought.  Not sure how to approach it.

**Comment by chrissimpkins** [comment]
Found the bug.  It is the way that I am parsing the filepath to construct the outfile path.   Working on a fix and will include it in the next release.

**Comment by chrissimpkins** [comment]
Fixed and the new release is available as v0.9.0 dev-2.  dmg installer available here:

https://github.com/chrissimpkins/Crunch/releases/download/v0.9.0-dev-2/Crunch-Installer.dmg

**Comment by herrbischoff** [comment]
Great, thank you. I can confirm that it works now.

**Comment by chrissimpkins** [comment]
^5!
