### ISSUE TITLE
crunch2 app exists with same application name

### ISSUE THREAD

**Issue by TraderStf** [chrissimpkins/Crunch#11]
crunch2.com
now https://getcrunch.co

> "If you like writing Less instead of CSS, you shouldn’t have to run scripts in your terminal like this is 1992, or install apps that do nothing except babysit your style files.
> 
> Crunch lets you write Less, Sass, CoffeeScript, Markdown*, and then automatically saves CSS, JavaScript, and HTML after you’ve made changes. Want to write just plain CSS? XML? Haskell? MUSHCode? Crunch lets you do that too.
> 
> Crunch 2 is an editor that lets you do what you want. Because Crunch loves you."

**Comment by chrissimpkins** [comment]
Sorry for the name collision... I would be happy to provide documentation on how to build this yourself with a new, different name if you would like to use both applications simultaneously.

**Comment by TraderStf** [comment]
Just FYI. No name collision, it's -crunch2- for quite a long time. :-)

**Comment by chrissimpkins** [comment]
@TraderStf thank you!
