### ISSUE TITLE
Not working .dmg

### ISSUE THREAD

**Issue by aguadotzn** [chrissimpkins/Crunch#16]
Hi! I already installed the **.dmg** for mac (_High Sierra_), moved it into applications folder and then open it. After that, I try to drag files into the application but nothing happens...

**Comment by chrissimpkins** [comment]
The only thing that will happen in the application is that the animated 'spinner' will speed up while processing and then slow down again.   The image write takes place in the same directory as the original file with the filename, [original filename]-crunch.png.  

Can you confirm that you do not see the above with version 1.1.0?

**Comment by aguadotzn** [comment]
Yes, I did it like you describes but nothing happens... I tried with different images sizes
![Screenshot](https://user-images.githubusercontent.com/22575055/38164215-433a9284-3501-11e8-8fb8-18a6b585bff6.png)

**Comment by chrissimpkins** [comment]
Hmm... And only png images correct?

**Comment by aguadotzn** [comment]
Oh sorry for the inconvenience, was my fault. I only tried with fake png images... Sorry! And thanks! Working well, good job man 😊

**Comment by chrissimpkins** [comment]
I like these problems! They are simple to solve.  Let me know if you see any problems with real png images.  It won't do anything with files that do not have a .png extension (and is a valid png file).  Enjoy!
