### ISSUE TITLE
PNG Format partially working

### ISSUE THREAD

**Issue by garyjacobs** [chrissimpkins/Crunch#25]
Hi Chris,

Attached are the PNG images in question.
They were all exported from Sketch from a single symbol. So in theory they are all the same image just at different sizes.

![spacexflight3l](https://user-images.githubusercontent.com/38194997/40090902-012a95f4-58f8-11e8-9377-65db30cbb4ac.png)
![spacexflight3m](https://user-images.githubusercontent.com/38194997/40090903-015f0c62-58f8-11e8-8fcd-351d90d0d081.png)
![spacexflight3s](https://user-images.githubusercontent.com/38194997/40090905-01a397b0-58f8-11e8-8cea-99f44392f69a.png)
![spacexflight3t](https://user-images.githubusercontent.com/38194997/40090906-01dc69b4-58f8-11e8-91b6-1966b03d1caa.png)

**Comment by chrissimpkins** [comment]
Do you mind copy/pasting in the filepaths that you are using for these images?  Github renames them and I want to confirm that it is not something with the file name that is causing an issue

**Comment by garyjacobs** [comment]
Sure! Here are the file names.
![image](https://user-images.githubusercontent.com/38194997/40091167-73fdb916-58f9-11e8-8d0e-9c4b3058c090.png)

**Comment by chrissimpkins** [comment]
Identified the problem.  The pngquant run on two of the files yields images with quality that measure below the set min value.  It raises a non-zero exit status code that is causing the file processing to end execution on two of those files.  Working on a fix.  Should be available in a bit.

**Comment by garyjacobs** [comment]
Cool! I saw the "pngquant" error flash in the GUI but had no idea what it was about. 🙏
Thanks for being speedy!

**Comment by chrissimpkins** [comment]
I think that it is fixed.  Mind using this .dmg installer and running through images that you export in a similar fashion to the ones above?

https://github.com/chrissimpkins/Crunch/tree/dev/installer

It will show as v2.0.1-beta in the About window.  If this fixes the issue we will push it as v2.0.1

**Comment by chrissimpkins** [comment]
Those two images that you had problems with will not be as compressed as the other two files that were working previously.  For some reason, pngquant is struggling with them.  First time that I have come across this issue.

**Comment by garyjacobs** [comment]
Will do. Will report back in 5

**Comment by garyjacobs** [comment]
Worked!
You are right though - it did only take a bit off those problem files from 1.7MB to 1.5MB but the ohters worked a treat! Thanks again!

**Comment by chrissimpkins** [comment]
Excellent! Thanks for giving it a try.  I will push this bugfix now.

**Comment by chrissimpkins** [comment]
This fix is now available as v2.0.1.  I pushed a pull request to update the Homebrew cask (https://github.com/caskroom/homebrew-cask/pull/47293) and it should be available for Homebrew installs in the next several hours.

Thanks again for reporting this issue!
