### ISSUE TITLE
Only support PNG compression?

### ISSUE THREAD

**Issue by Jinxiansen** [chrissimpkins/Crunch#26]
Hello, it's a great privilege to see Crunch open source 👏🏼, but currently only support PNG compression?

> English is not my native language; please excuse typing errors.

🤔

**Comment by chrissimpkins** [comment]
That is correct.  It only supports PNG images.  What image type are you interested in?

**Comment by Jinxiansen** [comment]
jpg/gif .
😄

**Comment by chrissimpkins** [comment]
If you are on macOS, I would suggest having a look at ImageOptim.  It is a great open source tool and I believe that it processes both of those image types.

**Comment by Jinxiansen** [comment]
In the mac OS environment, but the effect of ImageOptim is not very satisfactory, slightly worse than the tinypng, but unfortunately tinypng is based on pngquant, but there is no open source plan.

**Comment by chrissimpkins** [comment]
Sorry!  Unlikely to expand this project beyond png files for now.  Another option is to read up on the compression executables that are available for those image types, install them, and drop into a terminal / write a script to use them.  This project started as one of my shell scripts that used pngquant/zopflipng.
