### ISSUE TITLE
Develop a Crunch Windows GUI application [Help Wanted]

### ISSUE THREAD

**Issue by zwl1619** [chrissimpkins/Crunch#28]
have a Windows GUI Application?

**Comment by chrissimpkins** [comment]
Agree this would be useful.  Likely not on the immediate horizon.  I would be interested to hear from Win users whether the command line executable works under Cygwin.

**Comment by ScottRFrost** [comment]
Python runs natively on Windows.  You shouldn't need Cygwin or WSL.

**Comment by chrissimpkins** [comment]
Thanks for the feedback.  The issue will be the compile of the pngquant and zopflipng executables (and use of make but that is optional) which are mandatory to run the tool.  Do you have an approach to compile those on Win without Cygwin?  We can improve the docs and consider a script to perform the Win install without make if someone is willing to contribute these things.

**Comment by ScottRFrost** [comment]
PngQuant has a [native Windows binary](https://pngquant.org/pngquant-windows.zip) and [zopflipng-bin](https://github.com/imagemin/zopflipng-bin) has CI windows builds on AppVeyor.

**Comment by chrissimpkins** [comment]
Ah interesting.  That may be the ticket.  Thank you very much! Let me look into it.  Would just need to take the install out of shell scripts / make and we should be able to eliminate the Linux subsystem style support requirement.  Have time/interest/knowledge to help with this?

**Comment by ScottRFrost** [comment]
Unfortunately no.  I'm a career-long .NET / Microsoft Stack developer.  I don't really know anything about Python or *nix Makefile builds.  I just saw this app linked on a news site and thought I would check it out.  I noticed there weren't windows builds even though it's mostly Python so I was going to raise an issue.

Wish I could help more!

**Comment by gavindsouza** [comment]
Making a cross platform GUI solution would be much preferred. How about [tkinter](https://docs.python.org/3/library/tk.html)?

**Comment by chrissimpkins** [comment]
@gavindsouza Do you have any experience with tkinter GUI development Gavin?

**Comment by gavindsouza** [comment]
Not a lot, I've only just used it a couple of times for simple interfaces, login, forms, etc. @chrissimpkins

**Comment by chrissimpkins** [comment]
That's my problem too :)   I don't have extensive experience with GUI development and unfortunately just don't have the time right now to dig into it.  Let's leave this open.  I am sure that I will return to this project at some stage or someone out there will lend their expertise to the problem.
