### ISSUE TITLE
Add Homebrew cask install ruby script via PR

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Crunch#3]
https://github.com/caskroom/homebrew-cask/pull/20638

**Comment by adidalal** [comment]
The command to add to your readme is a simple `brew cask install crunch` - Homebrew will automatically tap and install Homebrew Cask if the user doesn't already have it, they just new Homebrew itself installed.

**Comment by chrissimpkins** [comment]
from @adidalal : 

Check out cask-repair, it makes Cask updates like that quite easy (details in CONTRIBUTING)

ie. After you release a new version, simply run cask-repair -v {{new_version} crunch, and it'll automatically make the changes, create the PR, and fill out the template for you!

**Comment by chrissimpkins** [comment]
@adidalal 

> The command to add to your readme

Done!

> What I posted (below) is for you to minimize time between you releasing a new version and us (HBC) having that in our repo.

Excellent, thank you very much.  I will use this with the next release.  I really appreciate all of your help Aditya!

**Comment by adidalal** [comment]
FYI

`Upgrades to the latest version are automated in the brew update && brew upgrade workflow.` is actually not yet true - HBC doesn't have upgrade functionality yet. (There are many third-party scripts that do implement it, though)

An upgrade is `brew cask uninstall crunch && brew cask install crunch` - preferences etc. get saved and all, but it's (unfortunately) not yet as simple as you describe for users to update.

**Comment by chrissimpkins** [comment]
Thank you very much for the clarification.  I updated the README with the correct upgrade instructions per your correction.

**Comment by chrissimpkins** [comment]
cask-repair failed with the v0.10.0 update.  Issue reported in https://github.com/vitorgalvao/tiny-scripts/issues/124

**Comment by chrissimpkins** [comment]
Fixed with this suggestion https://github.com/vitorgalvao/tiny-scripts/issues/124#issuecomment-375518029:

> Delete ~/.config/hub and try again. “Bad credentials” means whatever info you’re using to log in is wrong (perhaps outdated).

followed by repeat execution of the command:

```
$ cask-repair -v 0.10.0 crunch
```
