### ISSUE TITLE
JPG support with jpegoptim?

### ISSUE THREAD

**Issue by pzelnip** [chrissimpkins/Crunch#42]
Right now I use Crunch for optimizing my pngs and a different tool (`jpegoptim` -- https://github.com/tjko/jpegoptim) for optimizing my jpegs.  It'd be nice if I could use crunch for both (ie only one command to remember instead of two).

**Comment by chrissimpkins** [comment]
Great suggestion, but I don't have any immediate plans to support multiple image types.  I haven't looked into whether we can improve upon other tools' jpg compression ratios and don't have any experience in this area.

Let's leave this open to see if anyone who knows more about the available jpg compression tooling weighs in.  If we are able to come up with a new approach that yields some improvement upon existing GUI tools or command line executable "wrappers" around the embedded compression applications in those tools, this becomes much higher priority work.  If you have knowledge about the jpg area and want to begin to experiment with jpg files, I am all for it.  Let's see data and what new dependencies we would need to support across the tools here.
