### ISSUE TITLE
Autoupdate macOS GUI with Homebrew cask

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Crunch#51]
Homebrew cask now supports the following command which will automatically update the Crunch macOS GUI installed through Homebrew cask to new releases since you last installed/updated:

```
$ brew cask upgrade
```

Thanks to @adidalal for this information in https://github.com/chrissimpkins/Crunch/issues/49#issuecomment-390818291.  Will update documentation on the README and in the macOS GUI About text.

TODO:

- [x] update macOS GUI About text with `homebrew cask upgrade` approach to upgrades
- [x] update macOS GUI repository documentation with `homebrew cask upgrade` approach to upgrades

**Comment by adidalal** [comment]
It’s `brew cask upgrade`, I believe.

**Comment by chrissimpkins** [comment]
Sorry thanks!  Typo, fixed.

**Comment by chrissimpkins** [comment]
Docs are updated with this information.  Thanks for letting me know!  This is very helpful.
