### ISSUE TITLE
Comparison to ImageOptim

### ISSUE THREAD

**Issue by gingerbeardman** [chrissimpkins/Crunch#6]
If this just different default settings compared to ImageOptim? 

PS: I used Platypus (progress bar) to do something like this in 2009  http://www.gingerbeardman.com/pngenie/

**Comment by chrissimpkins** [comment]
> If this just different default settings compared to ImageOptim?

Will start by saying that I love ImageOptim (and ImageAlpha!).  It's a great application and this was built for my personal use as an alternative to ImageOptim for png files.

Here are the differences:

Crunch uses a lossy approach by default whereas ImageOptim uses a lossless approach by default.  To get the pngquant optimizations it is necessary to run ImageAlpha before you run ImageOptim on files.  With the combination of both applications, there is likely a way to establish settings that lead to the same binaries that are produced with Crunch.  I found a set of pngquant and zopflipng lossy settings that achieve as minimal file sizes that I could achieve with minimal image degradation for the types of images that I work with.  This has become my default tool for compression of png files that I push anywhere with an intent for someone to download (including loading for views in a browser).  In general it creates production ready images across many image types. See the README for a few examples where it is not appropriate to use.  Clearly you should visually proof images before use :)

There is absolutely no rocket science going on here. This is simply a pngquant run followed by a zopflipng run using a shell script with a set of settings that I happened upon with a fair bit of experimentation across numerous images a couple of years ago.

Recent versions of ImageOptim now let you perform lossy optimization of png files.  The application did not when this application was initially built.  I need to update the benchmarks using lossy settings for ImageOptim as this is a more valid comparison (though one that still requires you to modify default settings in ImageOptim whereas here it is the only option and one that comes out of the box). 

Here is an example of where we are currently with file sizes and DSSIM scores on a single anecdotal test with an illustration vs. ImageOptim:

## Pre-optimized image

**Size**: 210,561 bytes

![gopher-hawk](https://user-images.githubusercontent.com/4249591/37875102-c30f4f2a-3008-11e8-99aa-aa2e7c4972d6.png)

## ImageOptim v1.8.0 Lossless

**Size**: 188,158 bytes
**DSSIM**: 0.000000

![gopher-hawk-imageoptim-lossless](https://user-images.githubusercontent.com/4249591/37875184-ac9ddb2a-3009-11e8-8f16-a47856070b98.png)

## ImageOptim v1.8.0 Lossy

Settings include:

- General: Strip png metadata
- Quality: Enable lossy minification with image quality 80%
- Optimization speed: Extra

**Size**: 64,590 bytes
**DSSIM**: 0.000023

![gopher-hawk-imageoptim-lossy](https://user-images.githubusercontent.com/4249591/37875315-fefb5568-300a-11e8-9945-d868c7dfc29f.png)


## Crunch v1.0.0

**Size**: 53,620 bytes
**DSSIM**: 0.000061

![gopher-hawk-crunch](https://user-images.githubusercontent.com/4249591/37875336-715f186a-300b-11e8-983e-058c23fdb6cf.png)

If you have any thoughts about how to achieve better images / better compression, let me know!  I am sure that there is further optimization gain to be had here.

**Comment by gingerbeardman** [comment]
Thanks for the info. I thin you should say u front quite clearly that this is lossy compression. 

Also, for long processes it's useful to see determinate progress of some sort rather than a indeterminate spinner. You can use Platypus progress style (as I did with PNGenie) or by using REFRESH keyword with the current textview.

**Comment by chrissimpkins** [comment]
> Thanks for the info. I think you should say up front, quite clearly, that this is lossy compression

Will do!  This is important and if it is not currently clear, it definitely should be.  Thanks Matt.

> Also, for long processes it's useful to see determinate progress of some sort rather than a indeterminate spinner. You can use Platypus progress style (as I did with PNGenie) or by using REFRESH keyword with the current textview.

Ideally, I would just learn ObjC / Swift and make a real macOS application 😄 

I can get at determinate progress data for each pngquant execution completion and each zopflipng execution for each image that is DnD on the application window.  The REFRESH trick did not work for me as described in the platypus documentation so I have had a bit of difficulty with the transition to the WebView approach.  It required some HTML/CSS kung fu and that is definitely not my area of expertise.  Let me see what I can do.  Prior to v1.0.0 it was a text window that displayed progress, processing data, sizes of the images as this was carried out.  I intentionally chose to go very, very simple with this release and make a clean, small, and IMO more attractive GUI window.  Let me see if I can come up with something that gets at informative progress information.

**Comment by chrissimpkins** [comment]
> should say up front, quite clearly, that this is lossy compression

added to README in https://github.com/chrissimpkins/Crunch/commit/ef0efc03ed7add096ade9d19e07c7e38db2ca6ad

**Comment by denji** [comment]
@chrissimpkins Add tag: [`lossy`](https://github.com/topics/lossy).

**Comment by chrissimpkins** [comment]
@denji 

> Add tag: lossy.

Done!  added lossy-compression too...  ty!
