### ISSUE TITLE
Possibly helpful: A faster Guetzli fork (jpeg compression)

### ISSUE THREAD

**Issue by kurtextrem** [chrissimpkins/Crunch#65]
I'll just leave this here as "fyi": https://github.com/ianhuang-777/guetzli-cuda-opencl
Not sure if you have any use.

**Comment by chrissimpkins** [comment]
Looks good!  Associated IR https://github.com/chrissimpkins/Crunch/issues/42

Let me give some thought about moving into jpeg.  Will take a more detailed look.  Thanks for sharing this.
