### ISSUE TITLE
pngquant libraries not loaded dmg installer & homebrew cask install approaches (libpng + little-cms2) [fixed!]

### ISSUE THREAD

**Issue by soundage** [chrissimpkins/Crunch#7]
After installing wthe DMG file and dragging the PNG, this is what I got:

dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib Referenced from: /Applications/Crunch.app/Contents/Resources/./pngquant Reason: image not found /Applications/Crunch.app/Contents/Resources/script: line 10: 6549 Abort trap: 6 ./pngquant --quality=80-98 --skip-if-larger --force --ext -crunch.png "$imagepath" > /dev/null

@chrissimpkins edits below -------

Associated closed issue reports to limit discussion to this thread:

https://github.com/chrissimpkins/Crunch/issues/10
https://github.com/chrissimpkins/Crunch/issues/12

TODO:

- [x] update homebrew cask install script with pngquant dependencies (fix confirmed for those who install with homebrew cask in https://github.com/chrissimpkins/Crunch/issues/7#issuecomment-376186143)
- [X] definitive solution is to use static linking for these libraries in the pngquant compile.  New issue report https://github.com/chrissimpkins/Crunch/issues/13 opened to address this.  A new release will be prepared with this fix.  I think that a transition to dynamic library linking may have happened at some stage along the way in the pngquant compile and I missed it... (this should be fixed in v1.0.1, awaiting confirmation)

### For those who previously used the Homebrew Cask installer

Try to install with the Homebrew cask install approach again.  The installer script was updated with a couple of new dependencies and this should now be fixed

### For those who want to install with the dmg installer

Please attempt your install with the v1.0.1 build.  This should be the fix for this issue.  Feedback needed to confirm and close this issue report.

https://github.com/chrissimpkins/Crunch/releases/tag/v1.0.1

**Comment by chrissimpkins** [comment]
If you happen to have access to Homebrew can I ask you to install libpng with the following and try again?

```
$ brew install libpng
```

If that works I will update the docs with this dependency.  Sorry I didn't realize this was an issue.  Thanks for reporting it.

**Comment by kevinrajaram** [comment]
Had the same issue and installing libpng fixed that!

Another issue arose:

`dyld: Library not loaded: /usr/local/opt/little-cms2/lib/liblcms2.2.dylib Referenced from: /Applications/Crunch.app/Contents/Resources/./pngquant Reason: image not found /Applications/Crunch.app/Contents/Resources/script: line 10: 26240 Abort trap: 6 ./pngquant --quality=80-98 --skip-if-larger --force --ext -crunch.png "$imagepath" > /dev/null`

Installing pngquant fixed up everything for me and now it's working flawless!
`brew install pngquant`

Hopes this helps others if they run into similar issues.

**Comment by chrissimpkins** [comment]
Verified both of those are pngquant dependencies in the pngquant homebrew Ruby installer script:

https://github.com/Homebrew/homebrew-core/blob/49a2074c5eb2c6ce836adc4f75cd8f7dd75acb6a/Formula/pngquant.rb#L17-L18

**Comment by chrissimpkins** [comment]
Here is what we need in the Crunch installer:

```rb
depends_on formula: [ 'libpng', 'little-cms2']
```

**Comment by chrissimpkins** [comment]
The Homebrew Cask PR was merged.   @soundage mind trying the install with Homebrew Cask again and let me know if this fixes the issue for you (or can someone else please confirm)?

**Comment by olssonm** [comment]
I had the same issue before; but downloaded the latest Homebrew Cask and now it's working for me – great job!

**Comment by chrissimpkins** [comment]
Hooah! Thank you very much for the feedback @olssonm!  Much appreciated.  

And thanks for taking the time to report this issue @soundage.  Will leave open until I update the documentation for those who use the dmg installer as this still affects them.

**Comment by chrissimpkins** [comment]
This should be fixed across as of v1.0.1 release.

dmg installer file is available here: https://github.com/chrissimpkins/Crunch/releases/download/v1.0.1/Crunch-Installer.dmg

Please confirm that this installs and executes without issues if you do not have libpng or little-cms2 installed through Homebrew on your system.

You can confirm this with `brew list` and inspection of your installed Homebrew packages.  There is a wide array of software that depends on libpng so this may be present for many.  Unknown (to me) how widely used little-cms2 is out there.

Will close if we have achieved a fix with the v1.0.1 release to address this issue.  

We should be able to eliminate the Homebrew install of these additional dependencies through the Homebrew cask installation approach if we are gtg with the current pngquant build.

**Comment by adidalal** [comment]
I was able to confirm that using the 1.0.1 .dmg build (without having libpng or little-cms2) works.


```bash
[~/Downloads] > brew list | grep libpng
[~/Downloads] > brew list | grep little-cms2
[~/Downloads] > 
```
Verified by crunching a [test](https://upload.wikimedia.org/wikipedia/commons/d/d9/Test.png) file using Crunch.app from the above link.

**Comment by chrissimpkins** [comment]
@adidalal Thank you very much Aditya!  Greatly appreciated!  Will close this as fixed.
