### ISSUE TITLE
[Feature Request] Low quality image placeholder.

### ISSUE THREAD

**Issue by rockmandash** [chrissimpkins/Crunch#70]
Hello, thank you for your wonderful image compression tool!
I would like to request features.
Is there any possibility that Crunch can have preview images generated also?
Like lqip, sqip or primitive: https://github.com/ondras/primitive.js
Thank you!

**Comment by chrissimpkins** [comment]
Thanks for the suggestion.  You are asking for a way to modify input images so that they are smaller and drawn with geometric primitives in order to use them as low quality previews on web pages?

**Comment by rockmandash** [comment]
@chrissimpkins Yes!

**Comment by chrissimpkins** [comment]
Going to be out of scope for this project.   You are aware of the Go project that does this?  It appears to support batch image processing.  The best approach would probably be to use that tool and follow it with the Crunch tooling.  If you are getting color reductions with the primitive transformation of the image, you are likely to see pretty significant file size reductions for your preview images.

**Comment by chrissimpkins** [comment]
Closing but feel free to keep the conversation going if you would like to discuss how Crunch could be used in that type of workflow.

**Comment by chrissimpkins** [comment]
@rockmandash have you tried using https://github.com/fogleman/primitive? It may be the tool that you need.  If you want to further optimize the images that come out of that tool you can process them with the pngquant / zopflipng approach that we are using here.  Will probably be very small files relative to where you start because you are likely getting color palette reduction in the primitive shape transform step.   Crunch and its underlying tools will squish those images further for the delayed loading approaches used in web development.  Let me know if I can help with anything on the Crunch side of things.

**Comment by rockmandash** [comment]
@chrissimpkins Thank you for your explanation!
"further optimize the images that come out of that tool" seems will make the preview image extremely small XDDD.
There is also one tool based on this tech out there: https://github.com/cielito-lindo-productions/primitive.nextgen
But seems no mac release version, would have to clone to use it through node.js.

**Comment by chrissimpkins** [comment]
@rockmandash are you looking to make a GUI tool for the command line executable used to process images? That is something that is relatively simple and I would be happy to help you with it if you want to manage the project.

**Comment by rockmandash** [comment]
@chrissimpkins 
I might not able to manage the project, the algorithm behind the tech is hard, it will take months for me to understand it.

**Comment by chrissimpkins** [comment]
@rockmandash I mean a GUI wrapper around the Go tool for the macOS platform.

**Comment by rockmandash** [comment]
@chrissimpkins I only familiar "Electron & Javascript".
Your crunch GUI tool seems more difficult. That's why your app so small (2.3mb).

**Comment by chrissimpkins** [comment]
Is it possible to set a default combination of settings in this group:

https://github.com/fogleman/primitive#command-line-usage

that would not need to be changed image to image?

**Comment by chrissimpkins** [comment]
@rockmandash OK, if you ever want to dig into it let me know.  If it is possible to settle on a standard set of settings that do not change it is possible to build a tool that is the same as the GUI drag and drop tool here.  We would build the GUI around the Go executable.
