### ISSUE TITLE
About Benchmarks

### ISSUE THREAD

**Issue by YuiZh0u** [chrissimpkins/Crunch#71]
Is there a file where I can see the benchmarks among the photos that I have compressed?

**Comment by chrissimpkins** [comment]
I'm not sure that I fully understand your question.  Do you mean that you'd like a script to test the benchmarks yourself (i.e. Crunch vs. other compression tools)?

**Comment by YuiZh0u** [comment]
I mean a file where I can see this data (see photo) like the ones you put, like the DSSIM, or were these values manually put in the table?

<img width="484" alt="Captura de pantalla 2019-09-11 a la(s) 16 29 52" src="https://user-images.githubusercontent.com/27017306/64728478-688ece00-d4b1-11e9-9233-ce8e0515015d.png">

**Comment by chrissimpkins** [comment]
Ah, yes those were all manually entered.  It looks like the zip archive was removed from the site where it is linked in that benchmarking document.  I don't know if Cédric Louvrier is still maintaining that site or not, but there appear to be a new set of files for use in benchmarking the pango application that is now listed on that site: https://css-ig.net/png-tools-overview.php

**Comment by chrissimpkins** [comment]
Feel free to reopen if there is anything else that you need.

**Comment by YuiZh0u** [comment]
Why Crunch didn't work with this photo?

![desierto](https://user-images.githubusercontent.com/27017306/64730926-8ca0de00-d4b6-11e9-99bb-b9840f480ef3.png)
