### ISSUE TITLE
Be more up front that this is lossy compression

### ISSUE THREAD

**Issue by gingerbeardman** [chrissimpkins/Crunch#8]
I think you should say up front, quite clearly, that this is lossy compression. I wasn't aware of that until you mentioned in another issue. 

The word lossy is only mentioned once in the README in the "Examples" section. 

Given that repeat processing of the same file can degrade image quality it's quite important for people to know they should keep their master images around.

**Comment by chrissimpkins** [comment]
You mean the fatal flaw of assuming users read the documentation is at play here ;)

Of course, happy to do this.  Good suggestion.

**Comment by chrissimpkins** [comment]
Added to first line of the introductory paragraph in https://github.com/chrissimpkins/Crunch/commit/ef0efc03ed7add096ade9d19e07c7e38db2ca6ad.  Thanks Matt!
