### ISSUE TITLE
Installation is failed using latest Homebrew in macOS

### ISSUE THREAD

**Issue by kawarimidoll** [chrissimpkins/Crunch#85]
The command `brew cask install` in `docs/MACOSGUI.md` doesn't work now because of update of Homebrew.
This is not a bug of this app, but the document needs to be fixed.

homebrew discussions: [Error: Calling brew cask install is disabled! · Discussion #340 · Homebrew/discussions](https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364)

> `brew cask <command>` was deprecated in favor of `brew <command> --cask` in Homebrew 2.6.0. Now that 2.7.0 has been released, they have been disabled.

homebrew blog: [2.6.0 — Homebrew](https://brew.sh/2020/12/01/homebrew-2.6.0/)

> All brew cask commands have been deprecated in favour of brew commands (with --cask) when necessary

screenshot:
![Calling brew cask install is disabled](https://user-images.githubusercontent.com/8146876/104828843-b9d27d00-58b0-11eb-89e3-5bae2c37747b.png)

**Comment by chrissimpkins** [comment]
Thank you very much for raising this issue!  Will merge #86 with your doc updates to address this issue.

My understanding is that the `brew cask` subcommand was deprecated in homebrew v2.6.0 and **removed** in homebrew v2.7.0.  All macOS users of homebrew v2.7.0 must move to this new installation approach.

**Comment by chrissimpkins** [comment]
Excellent documentation, links, and justification here btw.  I can't express strongly enough how nice it is to receive an issue thread that is easy to review!
