### ISSUE TITLE
is Fast PNG compression possible?

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [chrissimpkins/Crunch#88]
Hello,

I have configured Cruch in my Windows OS using WSL. The Crunch takes around 1-2 seconds to compress a single PNG image. Can we speed up this process (by using GPU or any other way) so that the resultant compression process may take 0.1 seconds or less?

Please answer this question.

**Comment by chrissimpkins** [comment]
Not that I am aware of.  This is a limitation of the implementations used to optimize the files and the size/speed balance we try to strike here.  It might be worth trying pngquant and zopflipng executables directly with different sets of acceptable options to see how close you can get.  My experience is that you won't turn a file that takes multiple seconds into one that runs in the sub-second range with these tools.  Let us know if you come across a better approach.
