### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by RDKRACZ** [chrissimpkins/Crunch#91]
**Describe the bug**
I get this when I try to run any crunch command
![image](https://user-images.githubusercontent.com/43277609/158865738-c8f48546-6131-4759-8657-a5d9409d181c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: just cloned via git

**Comment by RDKRACZ** [comment]
Workaround is working and `/usr/bin/env python` returns the same error but `/usr/bin/env python3` works

**Comment by chrissimpkins** [comment]
Did that work? If so, we should probably consider a move to release it like this.  I think that python3 should be supported on target platforms.   What distro are you using?

**Comment by faimin** [comment]
I cd to `/Applications/Crunch.app/Contents/Resources/crunch.py`, and update this script file env to `#!/usr/bin/env python3` directly, it work. 

OS: `macOS Monterey 12.3`
install *crunch* with `homebrew`
